### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by rajenur** [szilard/teach-data-science-msc-analytics-ceu#3]
The project due date is February 20. I leave to SF February 15, so if you need feedback on your work, please try to do so before then. 

Project guidelines:
https://github.com/szilard/teach-data-science-msc-analytics-ceu/blob/master/3-assessment/2-homework_data_analysis_project.md

**Comment by szilard** [comment]
To be more precise the due date (and time) is Febr 20, 11:55am CET

You need to create a github account and upload the Rmd and html files to a github project and send me and Ryan the link.
